language: node_js
node_js:
- '6.9.1'


branches:
  only:
    - master
    - Google-maps

before_script:
  - npm install -g @angular/cli@1.6.4
  - npm i

script:
  - ng build --env=prod --base-href /terrain/
 

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: demo.firstmakers.com
  skip_cleanup: true
  upload-dir: terrain
  local_dir: dist
  on:
    branch: master

  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: demo.firstmakers.com
  skip_cleanup: true
  upload-dir: terrainG
  local_dir: dist
  on:
    branch: Google-maps


after_deploy:

notifications:
  email:
    on_failure: change
    on_success: change
